### PR TITLE
Update LIKE search in Store to be case insensitive

### PR DESCRIPTION
**Pull request by aslakknutsen**
- Add Tests to verify search_\* and get_\* methods used by REST API

### CODE REVIEW

**Comment by abompard** [comment]
This is good ! Thanks !
I do have a few "cosmetic" suggestions:
- the convention is no blankline between the docstring and the function body (I know it's not always clear)
- you may create a separate TestCase class for your tests and put your `add_search_data` in `setUp()`. Then you can store the listname and hash as instance variables to re-use them in tests.
- if your test function does not find anything, your tests will error out with an IndexError instead of failing. It would be better to check that the function actually found something with for example `self.assertEqual(len(emails), 1)`

Let me know if you have any questions.

**Comment by aslakknutsen** [comment]
Thank you! Yeah, was wondering about extracting it out. I'll get this fixed. :)

**Comment by aslakknutsen** [comment]
- Added store.search_xx().one() which should give a more clear message if multiple are found
- Added assertIsNotNone() on the result object which should give clear message if nothing is found
- Removed space between code and comment
- Created test_storm_store_fetch TestCase to collect fetch operations in one

Couldn't find a len() on the ResultSet returned by Storm, but guessing the combination of one() and assertIsNotNone() does the same from a "why the test is failing" clarity point of view.

**Comment by abompard** [comment]
Yeah, one() combined with assertIsNotNone is even better.
In Python you don't have to create a separate file when you want to create a class, so you could have put the new class at the end of the other file, but I agree it's clearer that way for such a long class.
However, why the "fetch" name in the file and the class ? Somethink like "search" seems more appropriate.
Sorry but I'm very picky about naming :-) From my point of view it's the first and most essential form of documentation.

**Comment by aslakknutsen** [comment]
> However, why the "fetch" name in the file and the class ? Somethink like "search" seems more appropriate.

Calling it Search was my first thought, but it also contain a few Getter tests. While technically the get's are 'searching' the database as well, we have a few methods named 'search_xx' which is more discovery oriented than a pure 'i know what i want get it'. 

The existing testcase was focused on INSERT operations, the new one is focused on SELECT operations. 

I wanted to use a name that combined both the concept of "searching and getting" and landed on Fetch to avoid the confusion between methods named search and database search(select) operations.
('Read' came up as an another option)

> From my point of view it's the first and most essential form of documentation.

Totally agree. :)

**Comment by abompard** [comment]
OK, now I understand :-)

**Pull request merged**
