### PR TITLE
Clean up pipermail attachments from email.content

### PR DESCRIPTION
**Pull request by aslakknutsen**
When loading an archive from pipermail, attachments are
described in the email body as "-- next part --" pr
attachment.

This is noise for the reader and should not be part of the
email.content displayed to the user. The complete original
message can still be seen in the raw view.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
My logic here is that: 

If the message is from a pipermail archive, it is not a is_multipart() message and will contain pipermails version of describing multipart by using the -- next part -- in the body. If it's from a mbox, it will be is_multipart() and the body probably won't contain the pipermail --- next part --- bits. 

Not sure if that logic holds up, but..

**Comment by abompard** [comment]
You can have non-multipart emails in an mbox too, but I guess only checking for pipermail markers can be limited to non-multipart emails, that may avoid some false-positives.

Concerning the code now. Two things.
- First, and that's being picky, but your assertion in the test can be rewritten as `self.assertFalse(blahblah in contents)` or `self.failIf(blahblah in contents)`.
- Second, and that's a bigger problem : in mailman 2, the "next line" marker in pipermail will be added to the archive in the language the server is running, it's a translated string. That makes it much harder to detect, since the best way would be to import mailman2's translations, and I'm not sure we can do that reliably.

Oh well, I gess it's a good start as it is :-)
Please change the assertion and I'll merge it.

**Comment by aslakknutsen** [comment]
assertion fixed. 

Gotta love multi linguistic markers. :)
Do you know of an example of this somewhere? 

Has this changed in Mailman 3?
Can we depend on both Mailman 2 and 3 ? Or just copy the translations over?

**Comment by abompard** [comment]
No example that I can think of, but the string is marked for translation in the MM2 source code. In Mailman 3, Pipermail is gone, and the problem with it :-)

The idea of copying the translations over makes me cry. I don't know about you, but I'd rather only detect English. And it's not even my native language.

**Comment by aslakknutsen** [comment]
> The idea of copying the translations over makes me cry. I don't know about you, but I'd rather only detect English. And it's not even my native language.

Sure.. It can be handled one pull request at a time if/when it comes up :)

**Pull request merged**
